version: "3.7"

services:

  backend:
    build:
      dockerfile: Dockerfile
      context: .
    image: tender/backend:latest
    ports:
      - "3333:3333"
    depends_on:
      - db
    networks:
      - tender-net

  db:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/pass
    volumes:
      - db-data:/data
    networks:
      - tender-net

volumes:
  db-data:

networks:
  tender-net:
