version: "3.7"

services:

  backend:
    build: .
    image: tender/backend:latest
    ports:
      - "3333:3333"
#    depends_on:
#      - db
    networks:
      - tender-net

#  db:
#    image: mongo
#    ports:
#      - "27017:27017"
#    volumes:
#      - db-data:/data/db
#    networks:
#      - tender-net
#
#volumes:
#  db-data:

networks:
  tender-net:
