version: "3.7"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    image: tender/backend:latest
    ports:
      - "3333:3333"
    depends_on:
      - neo4j_db
    networks:
      - tender-net

  neo4j_db:
    image: neo4j:4.2
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      - NEO4J_AUTH=${DATABASE_USERNAME}/${DATABASE_PASSWORD}
    volumes:
      - db-data:/data
    networks:
      - tender-net

volumes:
  db-data:

networks:
  tender-net:
