name: DEV Deploy Container Azure

on:
  push:
    branches: [develop]

env:
  AZURE_WEBAPP_NAME: tender-backend-dev
  CONTAINER_REGISTRY: ${{ secrets.REGISTRY_URL }}

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d
      - name: Sleep until Container Started
        uses: jakejarvis/wait-action@master
        with:
          time: "30s"
      - name: Test
        run: docker exec -i tender-backend_backend_1 npm test
        env:
          CI: true
      - name: Build and Push Container
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ env.CONTAINER_REGISTRY }}/tender-backend-dev:${{ github.sha }} -t ${{ env.CONTAINER_REGISTRY }}/tender-backend-dev:latest
          docker push ${{ env.CONTAINER_REGISTRY }}/tender-backend-dev
      - name: Deploy to DEV Server
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_DEV_PUBLISH_PROFILE }}
          images: ${{ env.CONTAINER_REGISTRY }}/tender-backend-dev:latest
